apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knowledge-provider-worker.envConfigMapName" . }}
  labels:
    {{- include "knowledge-provider-worker.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- include "common.envConfigMapData" . | trim | nindent 2 }}
