apiVersion: {{ include "common.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/env-config: {{ include "common.checksumAnnotation" . }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "template.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- end }}
      {{- with (include "common.imagePullSecrets" . | trim) }}
      {{- . | nindent 6 }}
      {{- end }}
      {{- with (include "common.podSecurityContext" .) }}
      securityContext:
        {{- . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "template.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with (include "common.securityContext" .) }}
          securityContext:
            {{- . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- with (include "common.env" . | trim) }}
          env:
            {{- . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "template.envConfigMapName" . }}
            {{- range .Values.envFromSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- with (include "common.probes" . | trim) }}
          {{- . | nindent 10 }}
          {{- end }}
          resources:
            {{- include "common.resources" . | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
