{{- if include "common.serviceAccount.enabled" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knowledge-provider-temporal.serviceAccountName" . }}
  labels:
    {{- include "knowledge-provider-temporal.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.serviceAccount.annotations (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
