apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.envConfigMapName" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with (include "oan-common.envConfigMapData" . | trim) }}
data:
  {{- . | nindent 2 }}
{{- else }}
data: {}
{{- end }}
