apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-adapter.fullname" . }}
  labels:
    {{- include "network-adapter.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.service.annotations (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "network-adapter.selectorLabels" . | nindent 4 }}
